### PR TITLE
changed indentation size from 2 to 4 spaces

### PR DESCRIPTION
**Pull request by hendrikbeneke**

### CODE REVIEW

**Comment by hendrikbeneke** [comment]
I've changed the indentation to 4 spaces as we discussed in last Friday's meeting. Please leave comments to discuss pros and cons about this change. We will have a few days to discuss it and eventually merge or reject.

**Comment by vinnylinck** [comment]
My eyes like 4 spaces, but I would go with 2 spaces. 4 spaces config means more characters, which may reduce the number of functions that CrankShaft (v8 optimizer) will detect as hot code.

Maybe I'm going to far on this, but every function with more than 600 characters on his inline source/body   won't be optmized (including code, comments and spaces).

I vote to keep 2.

**Comment by hendrikbeneke** [comment]
I personally prefer 2 spaces. Since we have a max line length of 140 character with 4 spaces we definitely will have to add many more line breaks.

**Comment by niahmiah** [comment]
I think the default should be 2, but old projects that already use 4 should just override the rule in the local .eslintrc so we do not need a huge whitespace commit to fix things

**Comment by hendrikbeneke** [comment]
In order to match the new code style we would approach it with 'The Boy Scout Rule'. So whenever you touch an existing file just lint it. Then over time we would move form 4 to 2 spaces. Even if we kept 4 spaces we still need to lint the whole file to get the rest fixed. Keeping 4 would not really be a benefit IMHO.

**Comment by vinnylinck** [comment]
agreed!

**Comment by vinnylinck** [comment]
So, If there is an agreement, let's close this PR.

**Pull request closed without merging**
